Lagt til kall mot axsys: hentAnsatte og hentTilganger
navikt/common-java-modules pull request #436
Opened 2021-03-29 12:23 UTC by stianStensli

2021-03-29 12:36 UTC, AlexGaard requested changes

2021-03-29 12:36 UTC, AlexGaard commented on client/pom.xml
> +        <dependency>
Trenger ikke spring for dette :p

2021-03-29 12:36 UTC, AlexGaard commented on client/src/main/java/no/nav/common/client/axsys/AxsysClient.java
> +public interface AxsysClient {
Burde extende HealthCheck interfacet i likhet med de andre klientene

2021-03-29 12:36 UTC, AlexGaard commented on client/src/main/java/no/nav/common/client/axsys/AxsysClientImpl.java
> +        Response response = client.newCall(request).execute();
Burde bruke try med resource slik som de andre klientene

2021-03-29 12:36 UTC, AlexGaard commented on client/src/main/java/no/nav/common/client/axsys/AxsysClientImpl.java
> +        Response response = client.newCall(request).execute();
Burde bruke try med resource slik som de andre klientene

2021-03-29 12:37 UTC, AlexGaard commented
Tror det hadde vært greit med en cachet klient også, slik som f.eks norg2

2021-03-29 13:12 UTC, AlexGaard commented on client/src/main/java/no/nav/common/client/axsys/AxsysClientImpl.java
> +    public AxsysClientImpl(String axsysUrl) {
Kan være greit med en overload av konstruktøren som tar inn både url og en client, slik at man kan bruke andre klienter enn baseClient()

2021-03-29 13:30 UTC, stianStensli commented on client/src/main/java/no/nav/common/client/axsys/AxsysClientImpl.java
> +        Response response = client.newCall(request).execute();
Er det ok å bare hardkode inn header verdier? Er det egentlig nødvendig 🤔 

                .header("Accept", "application/json")

2021-03-29 13:42 UTC, stianStensli commented on client/src/main/java/no/nav/common/client/axsys/AxsysClientImpl.java
> +        return HealthCheckUtils.pingUrl(joinPaths(axsysUrl, "/internal/isAlive"), client);
Litt usikker på denne healthchecken... Driver å tester det nå

2021-03-30 07:18 UTC, AlexGaard commented on client/src/main/java/no/nav/common/client/axsys/AxsysClientImpl.java
> +        Response response = client.newCall(request).execute();
Kan også bruke javax.ws.rs.core.HttpHeaders

2021-03-30 07:20 UTC, AlexGaard commented on client/src/main/java/no/nav/common/client/axsys/AxsysClientImpl.java
> +        Response response = client.newCall(request).execute();
Fra PdlClientImpl ` .header(ACCEPT, MEDIA_TYPE_JSON.toString())`

2021-03-30 07:24 UTC, AlexGaard commented on client/src/main/java/no/nav/common/client/axsys/AxsysClient.java
> +    AxsysEnheter hentTilganger(NavIdent veileder);
Tenker at det er bedre å returnere `List<AxsysEnhet>`. Da må det også flyttes litt på data klassen slik at AxsysEnhet får en egen fil, så kan du bruke en anonym innerklasse for AxsysEnheter.
Litt småpirk, men det burde også stå `NavIdent navIdent`

2021-03-30 07:25 UTC, AlexGaard commented on client/src/test/java/no/nav/common/client/axsys/AxsysClientTest.java
> +        System.out.println(client.hentAnsatte(new EnhetId("1234")));
Regner med at denne ikke skal være her :p

2021-03-30 07:27 UTC, AlexGaard commented on client/src/test/java/no/nav/common/client/axsys/AxsysClientTest.java
> +        assertEquals(client.hentTilganger(new NavIdent("Z123456")), jsonTilganger);
Kan også at headers som NAV_CONSUMER_ID og NAV_CALL_ID blir lagt på

2021-03-30 07:34 UTC, AlexGaard commented on client/src/main/java/no/nav/common/client/axsys/CachedAxsysClient.java
> +        this.axsysClient = axsysClient;
Tenker det kunne vært greit med en ekstra konstruktør for å spesifisere cacher selv, så kan man overstyre cachen hvis det er ønskelig.

2021-03-30 07:37 UTC, AlexGaard commented on client/src/main/java/no/nav/common/client/axsys/CachedAxsysClient.java
> +            .maximumSize(1000)
Der er ca 390 kontorer i norge, men vi kan sette 500 som max

2021-03-30 07:40 UTC, AlexGaard commented on client/src/main/java/no/nav/common/client/axsys/CachedAxsysClient.java
> +            .maximumSize(1000)
1000 virker litt lite, vi kan prøve å starte med 5000 istedenfor

2021-03-30 10:46 UTC, stianStensli commented on client/src/test/java/no/nav/common/client/utils/SystemPropertiesRule.java
> +public class SystemPropertiesRule implements MethodRule {
Jeg endte opp med å kopiere over denne filen fra test mappen i "test". Det hadde kanskje vært bedre å flytte denne filen ut i en util mappe i "test" så det er mulig å importe den igjennom maven?

2021-03-30 10:54 UTC, AlexGaard commented on client/src/main/java/no/nav/common/client/axsys/AxsysEnhetBruker.java
> +    private NavIdent appIdent;
Ikke så altfor viktig, men vi kunne flyttet denne klassen inn i AxsysClientImpl siden den ikke skal brukes av andre utenfor pakken.

2021-03-30 10:57 UTC, AlexGaard commented on client/src/test/java/no/nav/common/client/utils/SystemPropertiesRule.java
> +public class SystemPropertiesRule implements MethodRule {
Det er mulig hvis man bruker følgende
```
<dependency>
            <groupId>no.nav.common</groupId>
            <artifactId>test</artifactId>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
```

2021-03-30 11:00 UTC, AlexGaard commented on client/src/test/java/no/nav/common/client/axsys/AxsysClientTest.java
> +        MDC.put("jobId", jobId);
Bruk heller `MDCConstants.MDC_CALL_ID`

2021-03-30 13:50 UTC, stianStensli commented on client/src/main/java/no/nav/common/client/axsys/AxsysClientImpl.java
> +        return HealthCheckUtils.pingUrl(joinPaths(axsysUrl, "/internal/isAlive"), client);
Fant ikke helt ut av dette, syns det ser ut til at det kan fungere, men jeg er ikke sikker 🤷‍♂️

2021-03-30 13:54 UTC, AlexGaard approved these changes

2021-03-30 14:14 UTC, merged